Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - main
-  pull_request:
 
 jobs:
   validate:
@@ -35,9 +34,9 @@ jobs:
       - name: Configure Koofr authentication
         run: |
           test -n "${{ secrets.KOOFR_USER }}" || (echo "KOOFR_USER is missing" && exit 1)
-          test -n "${{ secrets.KOOFR_PASSWORD }}" || (echo "KOOFR_PASSWORD is missing" && exit 1)
+          test -n "${{ secrets.KOOFR_PASS }}" || (echo "KOOFR_PASS is missing" && exit 1)
           dvc remote modify --local koofr user "${{ secrets.KOOFR_USER }}"
-          dvc remote modify --local koofr password "${{ secrets.KOOFR_PASSWORD }}"
+          dvc remote modify --local koofr password "${{ secrets.KOOFR_PASS }}"
 
       - name: Pull data with DVC
         run: dvc pull -v
